### ISSUE TITLE
Access control exeption

### ISSUE THREAD

**Issue by MrGeorgen** [zaddok/moodle#1]
I get the following error while creating a user:
```
{"exception":"webservice_access_exception","errorcode":"accessexception","message":"Access control exception"}
panic: Access control exception. https://exam.redstoneunion.de/webservice/rest/server.php?wstoken=5ee41bb0f11b8f1c04412f2cb5c1a6c6&wsfunction=core_user_create_users&moodlewsrestformat=json&users[0][firstname]=Baum&users[0][lastname]=Garten&users[0][email]=Famefqwf%40qqff.de&users[0][username]=baum&users[0][password]=wfwHHHH54858%2A%2A%2A%23

goroutine 1 [running]:
main.main()
        /home/mrgeorgen/dev/go/RBU_account/moodle.go:9 +0x21e
exit status 2
```
code:
```
package main

import "github.com/zaddok/moodle"

func main() {
	moodle := moodle.NewMoodleApi("https://exam.redstoneunion.de/", "token")
	_, err := moodle.AddUser("Baum", "Garten",  "Famefqwf@qqff.de" ,  "baum", "wfwHHHH54858***#")
	if err != nil {
		panic(err)
	}
}
```
The web service has permission for auth_email_get_signup_settings and auth_email_signup_user

**Comment by zaddok** [comment]
@MrGeorgen Im surprised someone found and tried my hacked together code.    😀  I hope you eventually worked out which permission you needed to add. I add a large number of permissions to get all of our systems talking and I have never gone to the effort to work out which permissions are needed for which API calls.

**Comment by MrGeorgen** [comment]
>m surprised someone found and tried my hacked together code. grinning

It's sometimes quite funny finding small repos and often the are very usefull.
I actually didn't worked it out. I might just add all permissions, but my moodle
instance is not much used anyway.
